import { eventHandler } from 'h3'
import type { HrOffering } from '../../../app/types/hr/offering'

export const offerings: HrOffering[] = [
  {
    "id": 1,
    "image": "/img/stockphoto_1.jpg",
    "title": "Nutrition for Busy Professionals",
    "description": "Learn quick, healthy meal prep strategies tailored for a hectic work schedule.",
    "category": "nutrition",
    "type": "online",
    "duration": "45 min",
    "price": 500,
    "maxParticipants": 20,
    "status": "draft",
    "providerId": 1,
    "providerName": "Mindful Spaces"
  },
  {
    "id": 2,
    "image": "/img/stockphoto_2.jpg",
    "title": "Mindful Mondays — 8 Week Program",
    "description": "Start your week with purpose through guided meditation and intention-setting practices.",
    "category": "meditation",
    "type": "online",
    "duration": "60 min",
    "price": 2400,
    "maxParticipants": 30,
    "status": "published",
    "providerId": 1,
    "providerName": "Mindful Spaces"
  },
  {
    "id": 3,
    "image": "/img/stockphoto_3.jpg",
    "title": "Stress Resilience Workshop",
    "description": "Develop actionable tools to manage workplace stress and build emotional resilience.",
    "category": "stress-management",
    "type": "hybrid",
    "duration": "90 min",
    "price": 1800,
    "maxParticipants": 25,
    "status": "published",
    "providerId": 1,
    "providerName": "Mindful Spaces"
  },
  {
    "id": 4,
    "image": "/img/stockphoto_4.jpg",
    "title": "HIIT Bootcamp",
    "description": "High-intensity interval training designed to maximize calorie burn and improve cardiovascular health.",
    "category": "fitness",
    "type": "in-person",
    "duration": "60 min",
    "price": 1500,
    "maxParticipants": 15,
    "status": "published",
    "providerId": 1,
    "providerName": "Mindful Spaces"
  },
  {
    "id": 5,
    "image": "/img/stockphoto_5.jpg",
    "title": "Morning Yoga Flow",
    "description": "An energizing vinyasa flow to awaken the body and center the mind before your day begins.",
    "category": "fitness",
    "type": "online",
    "duration": "30 min",
    "price": 300,
    "maxParticipants": 50,
    "status": "published",
    "providerId": 1,
    "providerName": "Mindful Spaces"
  },
  {
    "id": 6,
    "image": "/img/stockphoto_6.jpg",
    "title": "Plant-Based Cooking Basics",
    "description": "Master the fundamentals of delicious, nutrient-dense plant-based cooking in your own kitchen.",
    "category": "nutrition",
    "type": "hybrid",
    "duration": "120 min",
    "price": 2000,
    "maxParticipants": 10,
    "status": "draft",
    "providerId": 1,
    "providerName": "Mindful Spaces"
  },
  {
    "id": 7,
    "image": "/img/stockphoto_7.jpg",
    "title": "Sleep Hygiene Masterclass",
    "description": "Discover science-backed techniques to improve your sleep quality and wake up feeling refreshed.",
    "category": "stress-management",
    "type": "online",
    "duration": "60 min",
    "price": 800,
    "maxParticipants": 100,
    "status": "published",
    "providerId": 1,
    "providerName": "Mindful Spaces"
  },
  {
    "id": 8,
    "image": "/img/stockphoto_8.jpg",
    "title": "Guided Sound Bath",
    "description": "Immerse yourself in deeply relaxing frequencies and vibrations using crystal singing bowls.",
    "category": "meditation",
    "type": "in-person",
    "duration": "75 min",
    "price": 3500,
    "maxParticipants": 12,
    "status": "archived",
    "providerId": 1,
    "providerName": "Mindful Spaces"
  },
  {
    "id": 9,
    "image": "/img/stockphoto_9.jpg",
    "title": "Strength Training 101",
    "description": "Learn proper form and foundational movements for building lean muscle safely.",
    "category": "fitness",
    "type": "in-person",
    "duration": "60 min",
    "price": 1200,
    "maxParticipants": 8,
    "status": "published",
    "providerId": 1,
    "providerName": "Mindful Spaces"
  },
  {
    "id": 10,
    "image": "/img/stockphoto_10.jpg",
    "title": "Emotional Eating Support Group",
    "description": "A safe, guided space to explore the relationship between emotions and eating habits.",
    "category": "nutrition",
    "type": "online",
    "duration": "90 min",
    "price": 1000,
    "maxParticipants": 15,
    "status": "published",
    "providerId": 1,
    "providerName": "Mindful Spaces"
  },
  {
    "id": 11,
    "image": "/img/stockphoto_11.jpg",
    "title": "Corporate Mindfulness Seminar",
    "description": "Tailored mindfulness strategies to boost team focus, communication, and overall well-being.",
    "category": "meditation",
    "type": "hybrid",
    "duration": "4 hours",
    "price": 15000,
    "maxParticipants": 200,
    "status": "published",
    "providerId": 1,
    "providerName": "Mindful Spaces"
  },
  {
    "id": 12,
    "image": "/img/stockphoto_12.jpg",
    "title": "Anxiety Reduction Techniques",
    "description": "Practical grounding exercises and cognitive reframing tools to lower daily anxiety.",
    "category": "stress-management",
    "type": "online",
    "duration": "60 min",
    "price": 600,
    "maxParticipants": 50,
    "status": "draft",
    "providerId": 1,
    "providerName": "Mindful Spaces"
  },
  {
    "id": 13,
    "image": "/img/stockphoto_13.jpg",
    "title": "Advanced Pilates",
    "description": "A challenging core-focused workout utilizing advanced pilates techniques and equipment.",
    "category": "fitness",
    "type": "in-person",
    "duration": "55 min",
    "price": 2500,
    "maxParticipants": 10,
    "status": "published",
    "providerId": 1,
    "providerName": "Mindful Spaces"
  },
  {
    "id": 14,
    "image": "/img/stockphoto_14.jpg",
    "title": "Macro Tracking Deep Dive",
    "description": "Understand how to calculate, track, and adjust macronutrients for your specific goals.",
    "category": "nutrition",
    "type": "online",
    "duration": "45 min",
    "price": 400,
    "maxParticipants": 40,
    "status": "archived",
    "providerId": 1,
    "providerName": "Mindful Spaces"
  },
  {
    "id": 15,
    "image": "/img/stockphoto_15.jpg",
    "title": "Breathwork for Beginners",
    "description": "A gentle introduction to conscious breathing techniques for stress relief and mental clarity.",
    "category": "meditation",
    "type": "online",
    "duration": "30 min",
    "price": 250,
    "maxParticipants": 60,
    "status": "published",
    "providerId": 1,
    "providerName": "Mindful Spaces"
  },
  {
    "id": 16,
    "image": "/img/stockphoto_16.jpg",
    "title": "Gut Health Fundamentals",
    "description": "Explore the gut-brain connection and learn evidence-based strategies for a healthier microbiome.",
    "category": "nutrition",
    "type": "online",
    "duration": "60 min",
    "price": 700,
    "maxParticipants": 45,
    "status": "published",
    "providerId": 1,
    "providerName": "Mindful Spaces"
  },
  {
    "id": 17,
    "image": "/img/stockphoto_17.jpg",
    "title": "Kettlebell Core Crush",
    "description": "A dynamic, full-body conditioning session centered on kettlebell movements and core stability.",
    "category": "fitness",
    "type": "in-person",
    "duration": "50 min",
    "price": 900,
    "maxParticipants": 12,
    "status": "published",
    "providerId": 1,
    "providerName": "Mindful Spaces"
  },
  {
    "id": 18,
    "image": "/img/stockphoto_18.jpg",
    "title": "Lunchtime Meditation Reset",
    "description": "A short midday meditation to recharge your mental energy and boost afternoon productivity.",
    "category": "meditation",
    "type": "online",
    "duration": "20 min",
    "price": 150,
    "maxParticipants": 100,
    "status": "published",
    "providerId": 1,
    "providerName": "Mindful Spaces"
  },
  {
    "id": 19,
    "image": "/img/stockphoto_19.jpg",
    "title": "Injury Prevention for Desk Workers",
    "description": "Targeted mobility drills and ergonomic advice to prevent common office-related injuries.",
    "category": "fitness",
    "type": "hybrid",
    "duration": "45 min",
    "price": 600,
    "maxParticipants": 30,
    "status": "draft",
    "providerId": 1,
    "providerName": "Mindful Spaces"
  }
]

export default eventHandler(() => offerings)
