import { eventHandler } from 'h3'
import type { Client } from '../../../app/types/provider/client'

export const clients: Client[] = [
  {
    id: 1,
    company: 'Northwind Labs',
    industry: 'Technology',
    contactName: 'Sarah Chen',
    contactEmail: 'schen@northwindlabs.com',
    employees: 320,
    location: 'San Francisco, CA',
    status: 'active',
    totalBookings: 8,
    completedBookings: 6,
    cancelledBookings: 0,
    totalParticipants: 340,
    totalSpend: 18200,
    lastBookingDate: '2026-07-13',
    memberSince: '2025-02-10'
  },
  {
    id: 2,
    company: 'Helio Finance',
    industry: 'Finance',
    contactName: 'Marcus Reid',
    contactEmail: 'mreid@heliofinance.com',
    employees: 150,
    location: 'New York, NY',
    status: 'active',
    totalBookings: 5,
    completedBookings: 4,
    cancelledBookings: 1,
    totalParticipants: 210,
    totalSpend: 11400,
    lastBookingDate: '2026-07-22',
    memberSince: '2025-04-18'
  },
  {
    id: 3,
    company: 'Apex Digital',
    industry: 'Marketing',
    contactName: 'Jenna Park',
    contactEmail: 'jpark@apexdigital.io',
    employees: 80,
    location: 'Austin, TX',
    status: 'active',
    totalBookings: 3,
    completedBookings: 2,
    cancelledBookings: 0,
    totalParticipants: 95,
    totalSpend: 4800,
    lastBookingDate: '2026-07-28',
    memberSince: '2025-06-01'
  },
  {
    id: 4,
    company: 'Blueridge Partners',
    industry: 'Consulting',
    contactName: 'Daniel Osei',
    contactEmail: 'dosei@blueridge.com',
    employees: 500,
    location: 'Chicago, IL',
    status: 'active',
    totalBookings: 12,
    completedBookings: 10,
    cancelledBookings: 1,
    totalParticipants: 820,
    totalSpend: 52000,
    lastBookingDate: '2026-08-05',
    memberSince: '2024-11-15'
  },
  {
    id: 5,
    company: 'Solaris Group',
    industry: 'Energy',
    contactName: 'Priya Menon',
    contactEmail: 'pmenon@solarisgroup.com',
    employees: 220,
    location: 'Houston, TX',
    status: 'inactive',
    totalBookings: 4,
    completedBookings: 4,
    cancelledBookings: 0,
    totalParticipants: 180,
    totalSpend: 7600,
    lastBookingDate: '2026-06-18',
    memberSince: '2025-01-20'
  },
  {
    id: 6,
    company: 'Crestline Media',
    industry: 'Media',
    contactName: 'Tom Hargreaves',
    contactEmail: 'tom@crestlinemedia.com',
    employees: 60,
    location: 'Los Angeles, CA',
    status: 'inactive',
    totalBookings: 2,
    completedBookings: 2,
    cancelledBookings: 0,
    totalParticipants: 48,
    totalSpend: 2400,
    lastBookingDate: '2026-06-25',
    memberSince: '2025-05-12'
  },
  {
    id: 7,
    company: 'Veritas Capital',
    industry: 'Finance',
    contactName: 'Olivia Brooks',
    contactEmail: 'obrooks@veritascap.com',
    employees: 90,
    location: 'Boston, MA',
    status: 'active',
    totalBookings: 6,
    completedBookings: 4,
    cancelledBookings: 0,
    totalParticipants: 310,
    totalSpend: 19800,
    lastBookingDate: '2026-07-30',
    memberSince: '2025-03-05'
  },
  {
    id: 8,
    company: 'Ironclad Systems',
    industry: 'Engineering',
    contactName: 'Ben Nakamura',
    contactEmail: 'bnakamura@ironclad.io',
    employees: 175,
    location: 'Seattle, WA',
    status: 'inactive',
    totalBookings: 3,
    completedBookings: 3,
    cancelledBookings: 0,
    totalParticipants: 145,
    totalSpend: 6900,
    lastBookingDate: '2026-06-10',
    memberSince: '2025-02-28'
  },
  {
    id: 9,
    company: 'Luminary Co.',
    industry: 'Retail',
    contactName: 'Aisha Williams',
    contactEmail: 'awilliams@luminaryco.com',
    employees: 45,
    location: 'Portland, OR',
    status: 'prospect',
    totalBookings: 1,
    completedBookings: 0,
    cancelledBookings: 1,
    totalParticipants: 12,
    totalSpend: 0,
    lastBookingDate: '2026-07-03',
    memberSince: '2026-06-15'
  },
  {
    id: 10,
    company: 'Zenith Consulting',
    industry: 'Consulting',
    contactName: 'Ryan Walsh',
    contactEmail: 'rwalsh@zenithco.com',
    employees: 400,
    location: 'Denver, CO',
    status: 'active',
    totalBookings: 9,
    completedBookings: 6,
    cancelledBookings: 0,
    totalParticipants: 540,
    totalSpend: 37200,
    lastBookingDate: '2026-08-12',
    memberSince: '2024-12-01'
  }
]

export default eventHandler(() => clients)
